INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(1, 4, 'Regény', 'Az utolsó mohikán', '1826', 'Kaland');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(2, 3, 'Regény', 'A század legnagyobb hazugsága', '2007', 'Történelmi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(3, 5, 'Regény', 'A mester és Margarita', '1967', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(4, 2, 'Regény', 'Egri csillagok', '1899', 'Történelmi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(5, 4, 'Regény', 'Vuk', '1965', 'Gyerekkönyv');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(6, 5, 'Regény', 'Az Élet Útjai', '2006', 'Önéletrajz');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(7, 4, 'Regény', 'Az aranyember', '1902', 'Történelmi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(8, 3, 'Regény', 'A katedrális', '1989', 'Történelmi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(9, 4, 'Regény', 'Harry Potter és a bölcsek köve', '1997', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(10, 5, 'Regény', 'A Szél Neve', '2007', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(11, 3, 'Regény', 'Az alkimista', '1988', 'Spiritualitás');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(12, 2, 'Regény', 'Az éhezők viadala', '2008', 'Sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(13, 4, 'Regény', 'Könyök a sötétben', '1999', 'Krimi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(14, 5, 'Regény', 'A hobbit', '1937', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(15, 4, 'Regény', 'A dzsungel könyve', '1894', 'Gyerekkönyv');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(16, 3, 'Regény', 'Momo', '1973', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(17, 5, 'Regény', 'Gyalog galopp', '1965', 'Humor');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(18, 4, 'Regény', 'A zöld íjász', '1885', 'Kaland');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(19, 2, 'Regény', 'A kis herceg', '1943', 'Filozófiai');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(20, 4, 'Regény', 'Egy darab szív', '2003', 'Romantikus');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(21, 3, 'Regény', 'A gyűrűk ura', '1954', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(22, 4, 'Regény', 'Anna Karenina', '1878', 'Önéletrajz');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(23, 5, 'Regény', 'A szabadság ötven árnyalata', '2011', 'Erotika');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(24, 2, 'Regény', 'Az élet dolgairól', '1998', 'Önéletrajz');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(25, 3, 'képregény', 'Watchmen', '1986', 'drama');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(26, 5, 'képregény', 'Maus', '1991', 'haboru');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(27, 4, 'képregény', 'Saga', '2012', 'scifi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(28, 4, 'képregény', 'Sandman', '1989', 'fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(29, 5, 'képregény', 'The Walking Dead', '2003', 'horror');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(30, 3, 'képregény', 'V for Vendetta', '1982', 'politika');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(31, 4, 'képregény', 'Preacher', '1995', 'fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(32, 5, 'képregény', 'Bone', '1991', 'fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(33, 3, 'képregény', 'Sin City', '1991', 'noir');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(34, 4, 'képregény', 'Hellboy', '1993', 'akcio');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(35, 5, 'képregény', 'Akira', '1982', 'scifi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(36, 3, 'képregény', 'The Boys', '2006', 'akcio');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(37, 4, 'képregény', 'Fables', '2002', 'fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(38, 5, 'képregény', 'Transmetropolitan', '1997', 'scifi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(39, 4, 'képregény', 'Y: The Last Man', '2002', 'akcio');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(40, 3, 'képregény', 'The Sandman: Overture', '2013', 'fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(41, 4, 'képregény', 'Black Hole', '2005', 'drama');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(42, 5, 'képregény', 'Persepolis', '2000', 'haboru');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(43, 4, 'képregény', '100 Bullets', '1999', 'noir');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(44, 3, 'képregény', 'American Splendor', '1976', 'memoar');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(45, 4, 'képregény', 'Daytripper', '2010', 'drama');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(46, 5, 'képregény', 'Batman: Year One', '1987', 'akcio');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(47, 3, 'képregény', 'Batman: The Dark Knight Returns', '1986', 'akcio');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(48, 4, 'képregény', 'The League of Extraordinary Gentlemen', '1999', 'fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(49, 5, 'képregény', 'Marvels', '1994', 'superhos');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(50, 3, 'képregény', 'Spider-Man: Blue', '2002', 'superhos');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(51, 4, 'képregény', 'The Umbrella Academy', '2007', 'scifi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(52, 4, 'képregény', 'Batman: The Long Halloween', '1996', 'szuperhős');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(53, 3, 'képregény', 'Watchmen', '1986', 'szuperhős');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(54, 5, 'képregény', 'Sandman', '1989', 'fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(55, 4, 'képregény', 'Preacher', '1995', 'humoros');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(56, 3, 'képregény', 'Hellboy', '1994', 'szuperhős');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(57, 4, 'képregény', 'V for Vendetta', '1988', 'szuperhős');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(58, 5, 'képregény', 'The Walking Dead', '2003', 'horror');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(59, 3, 'képregény', 'The Boys', '2006', 'szatirikus');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(60, 4, 'képregény', 'Sin City', '1991', 'noir');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(61, 5, 'képregény', 'Saga', '2012', 'sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(62, 4, 'képregény', 'Fables', '2002', 'fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(63, 3, 'képregény', 'Y: The Last Man', '2002', 'sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(64, 4, 'képregény', 'Transmetropolitan', '1997', 'sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(65, 5, 'képregény', 'Akira', '1982', 'sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(66, 3, 'képregény', 'Nausicaä of the Valley of the Wind', '1982', 'fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(67, 4, 'képregény', 'Dragon Ball', '1984', 'szuperhős');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(68, 5, 'képregény', 'One Piece', '1997', 'kaland');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(69, 3, 'képregény', 'Naruto', '1997', 'szuperhős');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(70, 4, 'képregény', 'Death Note', '2003', 'misztikus');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(71, 5, 'képregény', 'Fullmetal Alchemist', '2001', 'fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(72, 4, 'képregény', 'Attack on Titan', '2009', 'horror');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(73, 3, 'képregény', 'Black Butler', '2006', 'misztikus');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(74, 4, 'képregény', 'Bleach', '2001', 'szuperhős');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(75, 5, 'képregény', 'My Hero Academia', '2014', 'szuperhős');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(76, 3, 'képregény', 'Assassination Classroom', '2012', 'humoros');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(77, 4, 'képregény', 'Tokyo Ghoul', '2011', 'horror');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(78, 4, 'képregény', 'Batman: The Killing Joke', '1988', 'akcio');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(79, 4, 'CD', 'Thriller', '1982', 'Pop');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(80, 5, 'CD', 'Back in Black', '1980', 'Rock');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(81, 4, 'Regény', 'A kis herceg', '1943', 'Filozofikus');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(82, 3, 'Regény', 'Az úr sötét anyaga', '1995', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(83, 5, 'Regény', 'A csendes amerikai', '1955', 'Thriller');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(84, 4, 'Regény', 'Az idő rövid története', '1987', 'Sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(85, 5, 'Regény', 'A Szél neve', '2007', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(86, 3, 'Regény', 'Az alkimista', '1988', 'Spiritualis');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(87, 4, 'Regény', 'Az Oroszlán, a boszorkány és a ruhásszekrény', '1950', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(88, 3, 'Regény', 'Az éhezők viadala', '2008', 'Sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(89, 5, 'Regény', 'A bűnök szigete', '2003', 'Thriller');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(90, 4, 'Regény', 'Harry Potter és a bölcsek köve', '1997', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(91, 5, 'Regény', 'Az Egyik', '2014', 'Sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(92, 4, 'Regény', 'A Pillangó-hatás', '1999', 'Sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(93, 3, 'Regény', 'A bálna árnyéka', '1851', 'Klasszikus');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(94, 4, 'Regény', 'Szenvedélyek viharában', '1847', 'Klasszikus');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(95, 5, 'Regény', 'Az ötödik hegy', '1995', 'Filozofikus');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(96, 3, 'Regény', 'A szolgálólány meséje', '1985', 'Sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(97, 4, 'Regény', 'Az élet értelme', '1983', 'Filozofikus');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(98, 5, 'Regény', 'A Rémálmok álma', '1978', 'Horror');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(99, 4, 'Regény', 'Háború és béke', '1869', 'Klasszikus');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(100, 3, 'Regény', 'Az aranyszem', '1865', 'Klasszikus');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(101, 4, 'Regény', 'A pálforduló', '1975', 'Thriller');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(102, 5, 'Regény', 'Körbejárás a Holdon', '1865', 'Sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(103, 3, 'Regény', 'Holtak naplója', '2006', 'Horror');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(104, 3, 'CD', 'Nevermind', '1991', 'Grunge');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(105, 4, 'CD', 'The Dark Side of the Moon', '1973', 'Rock');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(106, 5, 'CD', 'Bad', '1987', 'Pop');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(107, 3, 'CD', 'Californication', '1999', 'Rock');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(108, 2, 'CD', 'Britney', '2001', 'Pop');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(109, 4, 'CD', 'Ten', '1991', 'Grunge');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(110, 5, 'CD', 'The Eminem Show', '2002', 'Hip Hop');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(111, 3, 'CD', 'Appetite for Destruction', '1987', 'Rock');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(112, 4, 'CD', 'Blood Sugar Sex Magik', '1991', 'Rock');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(113, 5, 'CD', 'Back to Black', '2006', 'Soul');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(114, 2, 'CD', 'Dangerously in Love', '2003', 'RnB');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(115, 4, 'CD', 'Legend', '1984', 'Reggae');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(116, 3, 'CD', 'In Utero', '1993', 'Grunge');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(117, 5, 'CD', 'The Joshua Tree', '1987', 'Rock');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(118, 4, 'CD', 'Hotel California', '1976', 'Rock');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(119, 3, 'CD', 'Sgt. Peppers Lonely Hearts Club Band', '1967', 'Rock');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(120, 2, 'CD', 'Oops!... I Did It Again', '2000', 'Pop');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(121, 4, 'Hangoskönyv', 'Harry Potter és a bölcsek köve', '2001', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(122, 5, 'Hangoskönyv', 'Az idő urai', '2005', 'Sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(123, 3, 'Hangoskönyv', 'Az élet, amit megadtak nekem', '2018', 'Életrajzi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(124, 2, 'Hangoskönyv', 'Az én XX. századom', '2016', 'Memoár');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(125, 4, 'Hangoskönyv', 'A testőr', '1999', 'Thriller');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(126, 5, 'Hangoskönyv', 'A mélység hangjai', '2009', 'Krimi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(127, 3, 'Hangoskönyv', 'Az emberi lét igazságosztója', '2017', 'Filozófiai');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(128, 4, 'Hangoskönyv', 'Az ördög színháza', '2012', 'Thriller');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(129, 3, 'Hangoskönyv', 'Az alkimista', '1988', 'Kalandregény');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(130, 5, 'Hangoskönyv', 'A százezer király csatája', '2013', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(131, 4, 'Hangoskönyv', 'A sötétség ötven árnyalata', '2011', 'Erotikus');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(132, 3, 'Hangoskönyv', 'Az elszabaduló autók', '2015', 'Kalandregény');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(133, 2, 'Hangoskönyv', 'Az időfutár', '2014', 'Sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(134, 4, 'Hangoskönyv', 'Az utolsó kívánság', '1993', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(135, 5, 'Hangoskönyv', 'A szél neve', '1985', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(136, 3, 'Hangoskönyv', 'A falka', '2020', 'Krimi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(137, 4, 'Hangoskönyv', 'Az élet titkai', '2016', 'Önismereti');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(138, 2, 'Hangoskönyv', 'A tűz jegyében', '2008', 'Történelmi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(139, 5, 'Hangoskönyv', 'Az állatfarm', '1945', 'Politikai');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(140, 3, 'Hangoskönyv', 'A négy egykerekű', '1961', 'Gyermekregény');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(141, 4, 'Hangoskönyv', 'A holtak szava', '2006', 'Horror');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(142, 5, 'Hangoskönyv', 'A katedrális', '2010', 'Történelmi regény');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(143, 3, 'Hangoskönyv', 'A vonzerő ereje', '2006', 'Önismereti');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(144, 4, 'Hangoskönyv', 'Az elveszett kód', '2009', 'Thriller');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(145, 5, 'Hangoskönyv', 'A szent grál', '2003', 'Történelmi regény');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(146, 2, 'Hangoskönyv', 'A belső hang', '2018', 'Önismereti');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(147, 4, 'Hangoskönyv', 'Az igazság pillanata', '2011', 'Thriller');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(148, 3, 'Hangoskönyv', 'A hópárduc fogságában', '2014', 'Kalandregény');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(149, 5, 'Hangoskönyv', 'A bíbor trón', '2005', 'Történelmi regény');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(150, 4, 'Hangoskönyv', 'A szörnyeteg árnyéka', '2016', 'Thriller');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(151, 3, 'Hangoskönyv', 'A boldogság választása', '2012', 'Önismereti');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(152, 4, 'Hangoskönyv', 'A bosszú ára', '2010', 'Krimi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(153, 2, 'Hangoskönyv', 'A megvilágosodás útja', '2008', 'Önismereti');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(154, 5, 'Hangoskönyv', 'Az idő urai', '2013', 'Sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(155, 4, 'Hangoskönyv', 'A rettegés foka', '2009', 'Thriller');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(156, 3, 'Hangoskönyv', 'A vágy színhelyei', '2015', 'Erotika');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(157, 5, 'Hangoskönyv', 'A dzsungel törvénye', '2006', 'Kalandregény');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(158, 4, 'Hangoskönyv', 'Az igazság kardja', '2012', 'Fantasy');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(159, 3, 'Hangoskönyv', 'A belső bölcsesség', '2010', 'Önismereti');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(160, 4, 'Hangoskönyv', 'A halál hívása', '2008', 'Thriller');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(161, 5, 'Hangoskönyv', 'Az elveszett idő nyomában', '2005', 'Sci-fi');
INSERT INTO BOOK_STORE_PRODUCT(id, review, type, name, production, genre) VALUES(162, 2, 'Hangoskönyv', 'A bennünk rejlő erő', '2017', 'Önismereti');

-- Az Aruhaz tabla feltoltese:ÁruházId, Típus, Helyszín, Kapacitás
INSERT INTO BOOK_STORE_STORE(id, type, place, capacity) VALUES(1, 'fizikai', 'Budapest, IX. kerület, Üllői út 182.', 750);
INSERT INTO BOOK_STORE_STORE(id, type, place, capacity) VALUES(2, 'fizikai', 'Debrecen, Nagyállomás utca 1.', 400);
INSERT INTO BOOK_STORE_STORE(id, type, place, capacity) VALUES(3, 'fizikai', 'Szeged, Tisza Lajos krt. 49.', 200);
INSERT INTO BOOK_STORE_STORE(id, type, place, capacity) VALUES(4, 'fizikai', 'Győr, Budai út 1.', 1000);
INSERT INTO BOOK_STORE_STORE(id, type, place, capacity) VALUES(5, 'fizikai', 'Pécs, Széchenyi tér 1.', 500);
INSERT INTO BOOK_STORE_STORE(id, type, place, capacity) VALUES(6, 'fizikai', 'Debrecen, Virág utca 10.', 400);
INSERT INTO BOOK_STORE_STORE(id, type, place, capacity) VALUES(7, 'fizikai', 'Szeged, Csap utca 90.', 600);
INSERT INTO BOOK_STORE_STORE(id, type, place, capacity) VALUES(8, 'fizikai', 'Csanádpalota, Hattyú utca 28.', 100);
INSERT INTO BOOK_STORE_STORE(id, type, place, capacity) VALUES(9, 'fizikai', 'Makó, Szegedi utca 22.', 300);
INSERT INTO BOOK_STORE_STORE(id, type, place, capacity) VALUES(10, 'fizikai', 'Vásárhely, Kiskakas út 3.', 600);
INSERT INTO BOOK_STORE_STORE(id, type, place, capacity) VALUES(11, 'fizikai', 'Eger, Ideges sor 67.', 500);
INSERT INTO BOOK_STORE_STORE(id, type, place, capacity) VALUES(12, 'online', 'online', 10.000);

-- A Felhasznalo tabla feltoltese: FelhasználóId, Név, Email, SzületésiIdő, ,  MegvásároltTermékekSzáma
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(1, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Kovács János', 'kovacs.janos@nevhu.com', TO_DATE('20-05-1975','dd mm yyyy'), 11, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(2, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Nagy Anna', 'nagy.anna@nevhu.com', TO_DATE('07-09-1983', 'dd mm yyyy'),16, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(3, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Tóth Gábor', 'toth.gabor@nevhu.com', TO_DATE('11-12-1972','dd mm yyyy'), 22, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(4, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Szabó Eszter', 'szabo.eszter@nevhu.com', TO_DATE('29-07-1965', 'dd mm yyyy'),6, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(5, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Kiss László', 'kiss.laszlo@nevhu.com', TO_DATE('14-02-1990','dd mm yyyy'), 9, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(6, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Horváth Mária', 'horvath.maria@nevhu.com',TO_DATE( '23-11-1987','dd mm yyyy'), 2, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(7, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Farkas Péter', 'farkas.peter@nevhu.com', TO_DATE('03-08-1964','dd mm yyyy'), 12, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(8, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Szűcs Judit', 'szucs.judit@nevhu.com', TO_DATE('28-04-1981','dd mm yyyy'), 25, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(9, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Varga Zsolt', 'varga.zsolt@nevhu.com', TO_DATE('01-06-1978', 'dd mm yyyy'),21, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(10, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Kerekes Éva', 'kerekes.eva@nevhu.com',TO_DATE( '12-03-1971','dd mm yyyy'), 27, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(11, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Balogh Béla', 'balogh.bela@nevhu.com', TO_DATE('18-09-1995', 'dd mm yyyy'),15, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(12, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Simon Andrea', 'simon.andrea@nevhu.com', TO_DATE('30-12-1973','dd mm yyyy'), 29, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(13, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Takács Csaba', 'takacs.csaba@nevhu.com', TO_DATE('06-07-1989','dd mm yyyy'), 23, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(14, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Fehér Zoltán', 'feher.zoltan@nevhu.com', TO_DATE('17-11-1979','dd mm yyyy'), 20, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(15, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Szőke Ildikó', 'szoke.ildiko@nevhu.com', TO_DATE('29-02-1968','dd mm yyyy'), 3, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(16, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Papp Dániel', 'papp.daniel@nevhu.com', TO_DATE('03-05-1992','dd mm yyyy'), 1, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(17, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Gáspár Zsuzsanna', 'gaspar.zsuzsanna@nevhu.com', TO_DATE('19-09-1986','dd mm yyyy'), 28, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(18, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Bíró István', 'biro.istvan@nevhu.com', TO_DATE('11-04-1980','dd mm yyyy'), 10, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(19, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Antal Adrienn', 'antal.adrienn@nevhu.com', TO_DATE('24-08-1976', 'dd mm yyyy'),19, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(20, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Fodor József', 'fodor.jozsef@nevhu.com', TO_DATE('07-01-1998', 'dd mm yyyy'),14, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(21, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Bálint Zsófia', 'balint.zsofia@valami.hu',TO_DATE( '11-09-1988', 'dd mm yyyy'),22, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(22, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Csont Dániel', 'csont.daniel@valami.hu', TO_DATE('07-05-1996', 'dd mm yyyy'),12, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(23, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Kovács László', 'kovacs.laszlo@valami.hu', TO_DATE('02-03-1981', 'dd mm yyyy'),16, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(24, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Budai István', 'budai.istvan@valami.hu', TO_DATE('24-12-1975', 'dd mm yyyy'),7, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(25, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Molnár Katalin', 'molnar.katalin@valami.hu', TO_DATE('13-07-1972', 'dd mm yyyy'),25, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(26, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Nagy Tamás', 'nagy.tamas@valami.hu', TO_DATE('18-02-1985', 'dd mm yyyy'),11, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(27, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Horváth Károly', 'horvath.karoly@valami.hu', TO_DATE('05-11-1990', 'dd mm yyyy'),19, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(28, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Pintér Anna', 'pinter.anna@valami.hu',TO_DATE( '08-08-1989', 'dd mm yyyy'),4, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(29, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Kiss Gergely', 'kiss.gergely@valami.hu', TO_DATE('19-04-1993', 'dd mm yyyy'),28, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(30, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Farkas Levente', 'farkas.levente@valami.hu', TO_DATE('01-01-1980','dd mm yyyy'), 13, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(31, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Tóth Kinga', 'toth.kinga@valami.hu', TO_DATE('27-06-1998', 'dd mm yyyy'),10, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(32, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Kertész Zsolt', 'kertesz.zsolt@valami.hu', TO_DATE('10-12-1978', 'dd mm yyyy'),3, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(33, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Simon Máté', 'simon.mate@valami.hu', TO_DATE( '23-02-1971', 'dd mm yyyy'),24, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(34, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Kiss Szilveszter', 'kiss.szilveszter@valami.hu', TO_DATE( '14-05-1977', 'dd mm yyyy'),12, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(35, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Fehér Krisztina', 'feher.krisztina@valami.hu', TO_DATE('14-11-1991','dd mm yyyy'), 5, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(36, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Balogh Balázs', 'balogh.balazs@valami.hu', TO_DATE('30-08-1997','dd mm yyyy'), 20, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(37, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Kis Ágnes', 'kis.agnes@valami.hu', TO_DATE('06-05-1977', 'dd mm yyyy'),15, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(38, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Németh András', 'nemeth.andras@valami.hu', TO_DATE('11-03-1983', 'dd mm yyyy'),23, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(39, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Takács Zsuzsanna', 'takacs.zsuzsanna@valami.hu', TO_DATE('17-12-1987', 'dd mm yyyy'),9, 0);
INSERT INTO BOOK_STORE_USER(id, password, name, email, birthdate, purchasedproducts, isregular) VALUES(40, 'e6837af0b5dcb5397c6bc8b52c0fb95aa49a3fea4303e274c7501f0857cb9b80', 'Pálfi Viktória', 'palfi.viktoria@valami.hu', TO_DATE('20-02-1995', 'dd mm yyyy'),27, 0);


-- A Vasarlas tabla feltoltese:
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(1, TO_DATE('02-01-2023','dd mm yyyy'), 55000, 4, 15);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(2, TO_DATE('05-01-2023','dd mm yyyy'), 82000, 3, 23);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(3, TO_DATE('10-01-2023','dd mm yyyy'), 45000, 2, 9);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(4, TO_DATE('11-01-2023','dd mm yyyy'), 30000, 5, 19);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(5, TO_DATE('15-01-2023','dd mm yyyy'), 68000, 4, 36);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(6, TO_DATE('20-01-2023','dd mm yyyy'), 74000, 2, 4);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(7, TO_DATE('22-01-2023','dd mm yyyy'), 6000, 1, 32);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(8, TO_DATE('25-01-2023','dd mm yyyy'), 94000, 3, 12);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(9, TO_DATE('30-01-2023','dd mm yyyy'), 15000, 5, 28);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(10, TO_DATE('01-02-2023','dd mm yyyy'), 45000, 4, 10);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(11, TO_DATE('03-02-2023','dd mm yyyy'), 80000, 2, 37);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(12, TO_DATE('06-02-2023','dd mm yyyy'), 22000, 3, 21);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(13, TO_DATE('09-02-2023','dd mm yyyy'), 66000, 1, 8);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(14, TO_DATE('12-02-2023','dd mm yyyy'), 51000, 5, 31);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(15, TO_DATE('15-02-2023','dd mm yyyy'), 94000, 4, 14);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(16, TO_DATE('18-02-2023','dd mm yyyy'), 3000, 2, 25);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(17, TO_DATE('20-02-2023','dd mm yyyy'), 88000, 3, 6);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(18, TO_DATE('24-02-2023','dd mm yyyy'), 41000, 5, 17);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(19, TO_DATE('28-02-2023','dd mm yyyy'), 75000, 1, 39);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(20, TO_DATE('03-03-2023','dd mm yyyy'), 92000, 4, 29);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(21, TO_DATE('06-03-2023','dd mm yyyy'), 13000, 2, 2);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(22, TO_DATE('08-03-2023','dd mm yyyy'), 65000, 3, 35);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(23, TO_DATE('11-03-2023','dd mm yyyy'), 55000, 4, 11);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(24, TO_DATE('14-03-2023','dd mm yyyy'), 78000, 5, 26);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(25, TO_DATE('17-03-2023','dd mm yyyy'), 27000, 1, 3);
INSERT INTO BOOK_STORE_PURCHASE(id, dateofpurchase, price, review, user_id) VALUES(26, TO_DATE('22-03-2023','dd mm yyyy'), 99000, 2, 20);
